project:
  type: website
  output-dir: docs

website:
  title: "website"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: about.html
        text: About
      - href: hobbies.html
        text: Hobbies

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



